spring:
  datasource:
    url: jdbc:mysql://localhost:3306/edu_cs6460?useSSL=false
    username: root
    password: Ling
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: true
